version: '3'
services:
  task-manager:
    build: ./backend/task-manager
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=docker
      - MONGO_URI=mongodb://mongodb:27017/taskDB
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: