// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/modexp.proto

package modexp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModExpService_ComputeModExp_FullMethodName = "/modexp.ModExpService/ComputeModExp"
)

// ModExpServiceClient is the client API for ModExpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModExpServiceClient interface {
	ComputeModExp(ctx context.Context, in *ModExpRequest, opts ...grpc.CallOption) (*ModExpResponse, error)
}

type modExpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModExpServiceClient(cc grpc.ClientConnInterface) ModExpServiceClient {
	return &modExpServiceClient{cc}
}

func (c *modExpServiceClient) ComputeModExp(ctx context.Context, in *ModExpRequest, opts ...grpc.CallOption) (*ModExpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModExpResponse)
	err := c.cc.Invoke(ctx, ModExpService_ComputeModExp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModExpServiceServer is the server API for ModExpService service.
// All implementations must embed UnimplementedModExpServiceServer
// for forward compatibility.
type ModExpServiceServer interface {
	ComputeModExp(context.Context, *ModExpRequest) (*ModExpResponse, error)
	mustEmbedUnimplementedModExpServiceServer()
}

// UnimplementedModExpServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModExpServiceServer struct{}

func (UnimplementedModExpServiceServer) ComputeModExp(context.Context, *ModExpRequest) (*ModExpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeModExp not implemented")
}
func (UnimplementedModExpServiceServer) mustEmbedUnimplementedModExpServiceServer() {}
func (UnimplementedModExpServiceServer) testEmbeddedByValue()                       {}

// UnsafeModExpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModExpServiceServer will
// result in compilation errors.
type UnsafeModExpServiceServer interface {
	mustEmbedUnimplementedModExpServiceServer()
}

func RegisterModExpServiceServer(s grpc.ServiceRegistrar, srv ModExpServiceServer) {
	// If the following call pancis, it indicates UnimplementedModExpServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModExpService_ServiceDesc, srv)
}

func _ModExpService_ComputeModExp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModExpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModExpServiceServer).ComputeModExp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModExpService_ComputeModExp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModExpServiceServer).ComputeModExp(ctx, req.(*ModExpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModExpService_ServiceDesc is the grpc.ServiceDesc for ModExpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModExpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "modexp.ModExpService",
	HandlerType: (*ModExpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeModExp",
			Handler:    _ModExpService_ComputeModExp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/modexp.proto",
}
